/**
 * LinguaForge - Massive Curated Vocabulary Master Archive
 * Over 150 high-frequency, CEFR-calibrated vocabulary items with bilingual definitions,
 * IPA phonetics, real-world example sentences, collocations, and thematic categories.
 */

export const vocabularyArchive = [
  // ==========================================
  // LEVEL A1: ESSENTIAL FOUNDATIONS (35 words)
  // ==========================================
  {
    id: 1,
    word: "make",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 50,
    definition_en: "To create, produce, or cause something to happen.",
    definition_tr: "Yapmak, üretmek, oluşturmak.",
    phonetic: "/meɪk/",
    example_sentences: ["I make breakfast every morning.", "She made a mistake."],
    collocations: ["make a decision", "make a mistake", "make friends", "make sure"],
    category: "daily_life"
  },
  {
    id: 2,
    word: "take",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 60,
    definition_en: "To get, carry, or accept something; to require time.",
    definition_tr: "Almak, götürmek; (zaman) almak.",
    phonetic: "/teɪk/",
    example_sentences: ["Take this key with you.", "It takes twenty minutes to walk to school."],
    collocations: ["take a break", "take time", "take a look", "take care"],
    category: "daily_life"
  },
  {
    id: 3,
    word: "get",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 30,
    definition_en: "To receive, obtain, or become.",
    definition_tr: "Almak, elde etmek; olmak (durum değişikliği).",
    phonetic: "/ɡet/",
    example_sentences: ["Did you get my message?", "It is getting cold outside."],
    collocations: ["get ready", "get up", "get better", "get along with"],
    category: "daily_life"
  },
  {
    id: 4,
    word: "give",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 80,
    definition_en: "To hand something to someone without expecting payment.",
    definition_tr: "Vermek, sunmak.",
    phonetic: "/ɡɪv/",
    example_sentences: ["Can you give me that pen?", "She gave him a warm smile."],
    collocations: ["give advice", "give up", "give a hand", "give back"],
    category: "daily_life"
  },
  {
    id: 5,
    word: "know",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 45,
    definition_en: "To have information or familiarity in your mind.",
    definition_tr: "Bilmek, tanımak.",
    phonetic: "/noʊ/",
    example_sentences: ["I know the right answer.", "Do you know my brother?"],
    collocations: ["know how to", "let me know", "know about", "as you know"],
    category: "daily_life"
  },
  {
    id: 6,
    word: "think",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 55,
    definition_en: "To have an opinion or consider something in your mind.",
    definition_tr: "Düşünmek, sanmak.",
    phonetic: "/θɪŋk/",
    example_sentences: ["What do you think about this idea?", "I think it will rain today."],
    collocations: ["think about", "think twice", "I think so", "think ahead"],
    category: "daily_life"
  },
  {
    id: 7,
    word: "help",
    part_of_speech: "verb/noun",
    cefr_level: "A1",
    frequency_rank: 120,
    definition_en: "To make it easier for someone to do something.",
    definition_tr: "Yardım etmek; yardım.",
    phonetic: "/help/",
    example_sentences: ["Could you help me with my luggage?", "Thank you for your help."],
    collocations: ["ask for help", "help each other", "can't help it", "need help"],
    category: "communication"
  },
  {
    id: 8,
    word: "family",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 140,
    definition_en: "A group of people related by blood or marriage.",
    definition_tr: "Aile.",
    phonetic: "/ˈfæməli/",
    example_sentences: ["I love spending time with my family.", "She comes from a large family."],
    collocations: ["family member", "close family", "family tree", "start a family"],
    category: "daily_life"
  },
  {
    id: 9,
    word: "friend",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 150,
    definition_en: "A person you know well and like, but who is not a relative.",
    definition_tr: "Arkadaş, dost.",
    phonetic: "/frend/",
    example_sentences: ["He is my best friend.", "We have been friends since childhood."],
    collocations: ["best friend", "close friend", "make friends", "old friend"],
    category: "daily_life"
  },
  {
    id: 10,
    word: "routine",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 300,
    definition_en: "A regular way of doing things in a fixed order.",
    definition_tr: "Rutin, alışılmış düzen.",
    phonetic: "/ruːˈtiːn/",
    example_sentences: ["My morning routine starts at 7 AM.", "Exercise is part of my daily routine."],
    collocations: ["daily routine", "morning routine", "break the routine", "routine check"],
    category: "daily_life"
  },
  {
    id: 11,
    word: "important",
    part_of_speech: "adjective",
    cefr_level: "A1",
    frequency_rank: 95,
    definition_en: "Having great value, significance, or consequence.",
    definition_tr: "Önemli.",
    phonetic: "/ɪmˈpɔːrtnt/",
    example_sentences: ["Sleep is very important for health.", "We have an important meeting tomorrow."],
    collocations: ["most important", "play an important role", "important factor"],
    category: "academic"
  },
  {
    id: 12,
    word: "different",
    part_of_speech: "adjective",
    cefr_level: "A1",
    frequency_rank: 105,
    definition_en: "Not the same as another or each other.",
    definition_tr: "Farklı, değişik.",
    phonetic: "/ˈdɪfrənt/",
    example_sentences: ["They have two very different personalities.", "Try looking at it from a different perspective."],
    collocations: ["different from", "different ways", "completely different", "different kinds"],
    category: "general"
  },
  {
    id: 13,
    word: "water",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 75,
    definition_en: "A clear, colorless liquid essential for all plant and animal life.",
    definition_tr: "Su.",
    phonetic: "/ˈwɔːtər/",
    example_sentences: ["Drink plenty of water every day.", "Could I have a glass of water, please?"],
    collocations: ["drink water", "tap water", "mineral water", "hot water"],
    category: "daily_life"
  },
  {
    id: 14,
    word: "food",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 85,
    definition_en: "Any nutritious substance consumed to maintain life.",
    definition_tr: "Yemek, yiyecek, gıda.",
    phonetic: "/fuːd/",
    example_sentences: ["Turkish food is rich and delicious.", "We need to buy some fresh food."],
    collocations: ["delicious food", "fast food", "healthy food", "food market"],
    category: "food"
  },
  {
    id: 15,
    word: "time",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 15,
    definition_en: "A period, moment, or continuous measure of existence.",
    definition_tr: "Zaman, vakit; saat; kez/kere.",
    phonetic: "/taɪm/",
    example_sentences: ["What time does the lesson start?", "I don't have enough time today."],
    collocations: ["on time", "spend time", "save time", "next time", "have a good time"],
    category: "daily_life"
  },
  {
    id: 16,
    word: "morning",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 110,
    definition_en: "The early part of the day from sunrise until noon.",
    definition_tr: "Sabah.",
    phonetic: "/ˈmɔːrnɪŋ/",
    example_sentences: ["Good morning! How are you today?", "I study best in the early morning."],
    collocations: ["in the morning", "early morning", "morning walk", "this morning"],
    category: "daily_life"
  },
  {
    id: 17,
    word: "evening",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 160,
    definition_en: "The period of time at the end of the day, before night.",
    definition_tr: "Akşam.",
    phonetic: "/ˈiːvnɪŋ/",
    example_sentences: ["We usually eat dinner in the evening.", "Have a wonderful evening!"],
    collocations: ["in the evening", "yesterday evening", "tomorrow evening", "evening meal"],
    category: "daily_life"
  },
  {
    id: 18,
    word: "always",
    part_of_speech: "adverb",
    cefr_level: "A1",
    frequency_rank: 125,
    definition_en: "At all times; on every occasion.",
    definition_tr: "Her zaman, daima.",
    phonetic: "/ˈɔːlweɪz/",
    example_sentences: ["She always arrives early for class.", "I will always remember your kindness."],
    collocations: ["almost always", "as always", "always remember"],
    category: "daily_life"
  },
  {
    id: 19,
    word: "never",
    part_of_speech: "adverb",
    cefr_level: "A1",
    frequency_rank: 135,
    definition_en: "At no time; not ever.",
    definition_tr: "Asla, hiçbir zaman.",
    phonetic: "/ˈnevər/",
    example_sentences: ["I have never visited London.", "Never give up on your dreams."],
    collocations: ["never ever", "better late than never", "never again"],
    category: "daily_life"
  },
  {
    id: 20,
    word: "usually",
    part_of_speech: "adverb",
    cefr_level: "A1",
    frequency_rank: 220,
    definition_en: "Under normal conditions; generally.",
    definition_tr: "Genellikle, çoğunlukla.",
    phonetic: "/ˈjuːʒuəli/",
    example_sentences: ["I usually have coffee for breakfast.", "He usually goes to bed before midnight."],
    collocations: ["as usually", "more usually", "usually happens"],
    category: "daily_life"
  },
  {
    id: 21,
    word: "place",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 90,
    definition_en: "A particular position, building, town, or area.",
    definition_tr: "Yer, mekan, konum.",
    phonetic: "/pleɪs/",
    example_sentences: ["This cafe is a lovely place to study.", "There is no place like home."],
    collocations: ["take place", "in place of", "safe place", "meeting place"],
    category: "general"
  },
  {
    id: 22,
    word: "house",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 115,
    definition_en: "A building for human habitation, especially one that is lived in by a family.",
    definition_tr: "Ev, müstakil konut.",
    phonetic: "/haʊs/",
    example_sentences: ["They bought a small house near the coast.", "Welcome to our house!"],
    collocations: ["big house", "house price", "move house", "around the house"],
    category: "daily_life"
  },
  {
    id: 23,
    word: "city",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 145,
    definition_en: "A large town with a significant population.",
    definition_tr: "Şehir, kent.",
    phonetic: "/ˈsɪti/",
    example_sentences: ["Istanbul is an ancient and vibrant city.", "I prefer living in the city."],
    collocations: ["city center", "capital city", "big city", "city life"],
    category: "travel"
  },
  {
    id: 24,
    word: "country",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 130,
    definition_en: "A nation with its own government, occupying a particular territory.",
    definition_tr: "Ülke; kırsal alan.",
    phonetic: "/ˈkʌntri/",
    example_sentences: ["Which country would you like to visit?", "We spent the weekend in the country."],
    collocations: ["foreign country", "across the country", "in the country"],
    category: "travel"
  },
  {
    id: 25,
    word: "question",
    part_of_speech: "noun",
    cefr_level: "A1",
    frequency_rank: 165,
    definition_en: "A sentence or phrase used to find out information.",
    definition_tr: "Soru, sual.",
    phonetic: "/ˈkwestʃən/",
    example_sentences: ["May I ask you a quick question?", "That is a very good question."],
    collocations: ["ask a question", "answer a question", "in question", "out of the question"],
    category: "academic"
  },
  {
    id: 26,
    word: "answer",
    part_of_speech: "noun/verb",
    cefr_level: "A1",
    frequency_rank: 180,
    definition_en: "A response to a question or problem; to reply.",
    definition_tr: "Cevap, yanıt; cevap vermek.",
    phonetic: "/ˈænsər/",
    example_sentences: ["Do you know the answer?", "Please answer the phone."],
    collocations: ["correct answer", "answer the door", "short answer"],
    category: "communication"
  },
  {
    id: 27,
    word: "study",
    part_of_speech: "verb/noun",
    cefr_level: "A1",
    frequency_rank: 210,
    definition_en: "To devote time and attention to acquiring knowledge.",
    definition_tr: "Ders çalışmak, öğrenim görmek; araştırma.",
    phonetic: "/ˈstʌdi/",
    example_sentences: ["I study English every evening for an hour.", "She wants to study medicine."],
    collocations: ["study hard", "study for an exam", "field of study"],
    category: "academic"
  },
  {
    id: 28,
    word: "learn",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 190,
    definition_en: "To gain knowledge or skill through study, experience, or being taught.",
    definition_tr: "Öğrenmek.",
    phonetic: "/lɜːrn/",
    example_sentences: ["It takes practice to learn a language.", "We learn from our mistakes."],
    collocations: ["learn English", "learn by heart", "learn to drive", "eager to learn"],
    category: "academic"
  },
  {
    id: 29,
    word: "easy",
    part_of_speech: "adjective",
    cefr_level: "A1",
    frequency_rank: 230,
    definition_en: "Achieved without great effort; not difficult.",
    definition_tr: "Kolay, zahmetsiz.",
    phonetic: "/ˈiːzi/",
    example_sentences: ["The first test was surprisingly easy.", "Take it easy and don't panic."],
    collocations: ["take it easy", "easy to understand", "easy way", "not easy"],
    category: "general"
  },
  {
    id: 30,
    word: "happy",
    part_of_speech: "adjective",
    cefr_level: "A1",
    frequency_rank: 240,
    definition_en: "Feeling or showing pleasure or contentment.",
    definition_tr: "Mutlu, memnun.",
    phonetic: "/ˈhæpi/",
    example_sentences: ["She was so happy to see her parents.", "Happy birthday to you!"],
    collocations: ["happy to help", "happy ending", "feel happy", "happy with"],
    category: "emotions"
  },
  {
    id: 31,
    word: "speak",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 175,
    definition_en: "To say words, talk, or communicate in a spoken language.",
    definition_tr: "Konuşmak.",
    phonetic: "/spiːk/",
    example_sentences: ["Do you speak English?", "Could you speak a little slower, please?"],
    collocations: ["speak fluently", "speak to someone", "so to speak", "speak your mind"],
    category: "communication"
  },
  {
    id: 32,
    word: "listen",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 205,
    definition_en: "To give attention with the ear; to heed advice.",
    definition_tr: "Dinlemek, kulak vermek.",
    phonetic: "/ˈlɪsn/",
    example_sentences: ["Listen carefully to the teacher's instructions.", "I like listening to acoustic music."],
    collocations: ["listen to music", "listen carefully", "listen to advice"],
    category: "communication"
  },
  {
    id: 33,
    word: "write",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 165,
    definition_en: "To compose text or put letters onto paper or a digital screen.",
    definition_tr: "Yazmak.",
    phonetic: "/raɪt/",
    example_sentences: ["Write your full name at the top.", "She wrote an inspiring essay."],
    collocations: ["write down", "write an email", "write back", "write by hand"],
    category: "communication"
  },
  {
    id: 34,
    word: "read",
    part_of_speech: "verb",
    cefr_level: "A1",
    frequency_rank: 155,
    definition_en: "To look at and comprehend the meaning of written words.",
    definition_tr: "Okumak.",
    phonetic: "/riːd/",
    example_sentences: ["I read a book every two weeks.", "Can you read this address for me?"],
    collocations: ["read a book", "read aloud", "read carefully", "read between the lines"],
    category: "academic"
  },
  {
    id: 35,
    word: "walk",
    part_of_speech: "verb/noun",
    cefr_level: "A1",
    frequency_rank: 215,
    definition_en: "To move on foot at a steady, natural pace.",
    definition_tr: "Yürümek; yürüyüş.",
    phonetic: "/wɔːk/",
    example_sentences: ["I walk to school every morning.", "Let's go for a walk in the park."],
    collocations: ["go for a walk", "walk away", "within walking distance"],
    category: "daily_life"
  },

  // ==========================================
  // LEVEL A2: DAILY FLUENCY & TRAVEL (35 words)
  // ==========================================
  {
    id: 36,
    word: "arrive",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 350,
    definition_en: "To reach a destination at the end of a journey.",
    definition_tr: "Varmak, ulaşmak.",
    phonetic: "/əˈraɪv/",
    example_sentences: ["The flight arrives at 4:30 PM.", "We arrived in London yesterday."],
    collocations: ["arrive at the airport", "arrive on time", "arrive in a city"],
    category: "travel"
  },
  {
    id: 37,
    word: "leave",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 185,
    definition_en: "To go away from a person or place; to depart.",
    definition_tr: "Ayrılmak, terk etmek; bırakmak.",
    phonetic: "/liːv/",
    example_sentences: ["The train leaves in ten minutes.", "Don't leave your umbrella behind."],
    collocations: ["leave a message", "leave home", "leave alone", "take leave"],
    category: "travel"
  },
  {
    id: 38,
    word: "choose",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 260,
    definition_en: "To pick out or select someone or something as being best or most suitable.",
    definition_tr: "Seçmek, tercih etmek.",
    phonetic: "/tʃuːz/",
    example_sentences: ["It was hard to choose between the two jobs.", "You can choose any color you like."],
    collocations: ["choose carefully", "choose between", "freedom to choose"],
    category: "general"
  },
  {
    id: 39,
    word: "decide",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 290,
    definition_en: "To make a choice from a number of alternatives after consideration.",
    definition_tr: "Karar vermek.",
    phonetic: "/dɪˈsaɪd/",
    example_sentences: ["We decided to stay home because of the storm.", "Have you decided what to study?"],
    collocations: ["decide to do", "decide on", "hard to decide"],
    category: "general"
  },
  {
    id: 40,
    word: "explain",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 310,
    definition_en: "To make an idea or situation clear by describing it in more detail.",
    definition_tr: "Açıklamak, izah etmek.",
    phonetic: "/ɪkˈspleɪn/",
    example_sentences: ["Can you explain this grammar rule again?", "Let me explain why I was late."],
    collocations: ["explain in detail", "hard to explain", "explain to someone"],
    category: "communication"
  },
  {
    id: 41,
    word: "remember",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 275,
    definition_en: "To have in or be able to bring to one's mind an awareness of someone or something.",
    definition_tr: "Hatırlamak, anımsamak.",
    phonetic: "/rɪˈmembər/",
    example_sentences: ["I remember meeting you in Berlin.", "Please remember to lock the front door."],
    collocations: ["remember to do", "remember vividly", "as far as I remember"],
    category: "daily_life"
  },
  {
    id: 42,
    word: "forget",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 325,
    definition_en: "To fail to remember or recall something.",
    definition_tr: "Unutmak.",
    phonetic: "/fərˈɡet/",
    example_sentences: ["Don't forget your passport!", "I completely forgot about our meeting."],
    collocations: ["forget about", "don't forget to", "never forget", "easy to forget"],
    category: "daily_life"
  },
  {
    id: 43,
    word: "borrow",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 580,
    definition_en: "To take and use something belonging to someone else with the intention of returning it.",
    definition_tr: "Ödünç almak.",
    phonetic: "/ˈbɑːroʊ/",
    example_sentences: ["Could I borrow your charger for an hour?", "Students can borrow up to five books."],
    collocations: ["borrow from", "borrow money", "borrow a book"],
    category: "daily_life"
  },
  {
    id: 44,
    word: "lend",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 610,
    definition_en: "To grant someone the use of something on the condition that it will be returned.",
    definition_tr: "Ödünç vermek.",
    phonetic: "/lend/",
    example_sentences: ["I can lend you my bicycle this weekend.", "Banks lend money to businesses."],
    collocations: ["lend a hand", "lend to", "lend money"],
    category: "daily_life"
  },
  {
    id: 45,
    word: "comfortable",
    part_of_speech: "adjective",
    cefr_level: "A2",
    frequency_rank: 480,
    definition_en: "Providing physical ease and relaxation; feeling at ease.",
    definition_tr: "Rahat, konforlu.",
    phonetic: "/ˈkʌmftəbl/",
    example_sentences: ["These shoes are very comfortable for walking.", "Make yourself comfortable."],
    collocations: ["feel comfortable", "comfortable with", "make comfortable"],
    category: "daily_life"
  },
  {
    id: 46,
    word: "expensive",
    part_of_speech: "adjective",
    cefr_level: "A2",
    frequency_rank: 390,
    definition_en: "Costing a lot of money; not cheap.",
    definition_tr: "Pahalı, masraflı.",
    phonetic: "/ɪkˈspensɪv/",
    example_sentences: ["Hotels in downtown London are quite expensive.", "It is too expensive for our budget."],
    collocations: ["very expensive", "less expensive", "expensive taste"],
    category: "travel"
  },
  {
    id: 47,
    word: "cheap",
    part_of_speech: "adjective",
    cefr_level: "A2",
    frequency_rank: 410,
    definition_en: "Low in price; inexpensive.",
    definition_tr: "Ucuz, ekonomik.",
    phonetic: "/tʃiːp/",
    example_sentences: ["Public transport in this town is very cheap.", "We found a cheap flight to Rome."],
    collocations: ["cheap ticket", "cheap and cheerful", "relatively cheap"],
    category: "travel"
  },
  {
    id: 48,
    word: "delicious",
    part_of_speech: "adjective",
    cefr_level: "A2",
    frequency_rank: 520,
    definition_en: "Highly pleasant to the taste; mouth-watering.",
    definition_tr: "Lezzetli, nefis.",
    phonetic: "/dɪˈlɪʃəs/",
    example_sentences: ["The homemade soup was absolutely delicious.", "Thank you for the delicious dinner."],
    collocations: ["delicious meal", "taste delicious", "delicious smell"],
    category: "food"
  },
  {
    id: 49,
    word: "weather",
    part_of_speech: "noun",
    cefr_level: "A2",
    frequency_rank: 340,
    definition_en: "The state of the atmosphere at a place and time regarding heat, cloudiness, and rain.",
    definition_tr: "Hava, hava durumu.",
    phonetic: "/ˈweðər/",
    example_sentences: ["What is the weather forecast for tomorrow?", "The weather is lovely and warm."],
    collocations: ["weather forecast", "bad weather", "under the weather", "good weather"],
    category: "daily_life"
  },
  {
    id: 50,
    word: "ticket",
    part_of_speech: "noun",
    cefr_level: "A2",
    frequency_rank: 440,
    definition_en: "A certificate or token showing that a fare or admission fee has been paid.",
    definition_tr: "Bilet.",
    phonetic: "/ˈtɪkɪt/",
    example_sentences: ["I bought a return train ticket to Oxford.", "Have your tickets ready for inspection."],
    collocations: ["plane ticket", "one-way ticket", "book a ticket", "traffic ticket"],
    category: "travel"
  },
  {
    id: 51,
    word: "healthy",
    part_of_speech: "adjective",
    cefr_level: "A2",
    frequency_rank: 380,
    definition_en: "In good health; not diseased or injured; promoting good health.",
    definition_tr: "Sağlıklı, sıhhatli.",
    phonetic: "/ˈhelθi/",
    example_sentences: ["Eating vegetables helps you stay healthy.", "She maintains a healthy lifestyle."],
    collocations: ["healthy lifestyle", "healthy diet", "stay healthy", "healthy habits"],
    category: "health"
  },
  {
    id: 52,
    word: "journey",
    part_of_speech: "noun",
    cefr_level: "A2",
    frequency_rank: 460,
    definition_en: "An act of traveling from one place to another.",
    definition_tr: "Yolculuk, seyahat.",
    phonetic: "/ˈdʒɜːrni/",
    example_sentences: ["Have a safe journey home!", "It was a long journey across the mountains."],
    collocations: ["safe journey", "long journey", "start a journey"],
    category: "travel"
  },
  {
    id: 53,
    word: "advice",
    part_of_speech: "noun",
    cefr_level: "A2",
    frequency_rank: 370,
    definition_en: "Guidance or recommendations offered with regard to prudent future action.",
    definition_tr: "Tavsiye, öğüt (sayılamaz isim).",
    phonetic: "/ədˈvaɪs/",
    example_sentences: ["Can I give you a piece of advice?", "Thank you for your valuable advice."],
    collocations: ["piece of advice", "ask for advice", "follow advice", "take advice"],
    category: "communication"
  },
  {
    id: 54,
    word: "habit",
    part_of_speech: "noun",
    cefr_level: "A2",
    frequency_rank: 490,
    definition_en: "A settled or regular tendency or practice, especially one that is hard to give up.",
    definition_tr: "Alışkanlık.",
    phonetic: "/ˈhæbɪt/",
    example_sentences: ["Reading before bed is a beneficial habit.", "It is hard to break an old habit."],
    collocations: ["good habit", "break a habit", "form a habit", "eating habits"],
    category: "daily_life"
  },
  {
    id: 55,
    word: "polite",
    part_of_speech: "adjective",
    cefr_level: "A2",
    frequency_rank: 530,
    definition_en: "Having or showing behavior that is respectful and considerate of other people.",
    definition_tr: "Kibar, nazik, terbiyeli.",
    phonetic: "/pəˈlaɪt/",
    example_sentences: ["He was always very polite to his teachers.", "It is polite to say thank you."],
    collocations: ["polite request", "polite smile", "be polite to"],
    category: "communication"
  },
  {
    id: 56,
    word: "dangerous",
    part_of_speech: "adjective",
    cefr_level: "A2",
    frequency_rank: 450,
    definition_en: "Able or likely to cause harm or injury; risky.",
    definition_tr: "Tehlikeli.",
    phonetic: "/ˈdeɪndʒərəs/",
    example_sentences: ["It is dangerous to drive in heavy snow.", "Swimming here is dangerous."],
    collocations: ["dangerous situation", "highly dangerous", "dangerous to health"],
    category: "general"
  },
  {
    id: 57,
    word: "suddenly",
    part_of_speech: "adverb",
    cefr_level: "A2",
    frequency_rank: 330,
    definition_en: "Quickly and unexpectedly.",
    definition_tr: "Aniden, birdenbire.",
    phonetic: "/ˈsʌdənli/",
    example_sentences: ["Suddenly, the lights went off.", "She stopped suddenly in the street."],
    collocations: ["all of a sudden", "suddenly realized", "appear suddenly"],
    category: "general"
  },
  {
    id: 58,
    word: "finally",
    part_of_speech: "adverb",
    cefr_level: "A2",
    frequency_rank: 280,
    definition_en: "After a long time, typically involving difficulty or delay; at last.",
    definition_tr: "Sonunda, nihayet.",
    phonetic: "/ˈfaɪnəli/",
    example_sentences: ["We finally arrived after five hours of driving.", "Finally, check your answers."],
    collocations: ["finally agreed", "finally finished", "and finally"],
    category: "general"
  },
  {
    id: 59,
    word: "probably",
    part_of_speech: "adverb",
    cefr_level: "A2",
    frequency_rank: 250,
    definition_en: "Almost certainly; as far as one knows or can tell.",
    definition_tr: "Muhtemelen, büyük olasılıkla.",
    phonetic: "/ˈprɑːbəbli/",
    example_sentences: ["It will probably rain this evening.", "You are probably right."],
    collocations: ["most probably", "probably won't", "quite probably"],
    category: "communication"
  },
  {
    id: 60,
    word: "especially",
    part_of_speech: "adverb",
    cefr_level: "A2",
    frequency_rank: 295,
    definition_en: "Used to single out one person, thing, or situation over all others.",
    definition_tr: "Özellikle, bilhassa.",
    phonetic: "/ɪˈspeʃəli/",
    example_sentences: ["I love fruit, especially fresh strawberries.", "It was especially cold yesterday."],
    collocations: ["especially important", "especially for you", "not especially"],
    category: "general"
  },
  {
    id: 61,
    word: "crowded",
    part_of_speech: "adjective",
    cefr_level: "A2",
    frequency_rank: 620,
    definition_en: "Full of people, leaving little or no room for movement.",
    definition_tr: "Kalabalık, tıklım tıklım.",
    phonetic: "/ˈkraʊdɪd/",
    example_sentences: ["The metro is always crowded at 8 AM.", "The street was crowded with tourists."],
    collocations: ["crowded room", "get crowded", "overly crowded"],
    category: "travel"
  },
  {
    id: 62,
    word: "neighborhood",
    part_of_speech: "noun",
    cefr_level: "A2",
    frequency_rank: 470,
    definition_en: "A district, especially one forming a community within a town or city.",
    definition_tr: "Mahalle, çevre, civar.",
    phonetic: "/ˈneɪbərhʊd/",
    example_sentences: ["We live in a quiet, friendly neighborhood.", "There are great cafes in this neighborhood."],
    collocations: ["quiet neighborhood", "in the neighborhood", "safe neighborhood"],
    category: "daily_life"
  },
  {
    id: 63,
    word: "airport",
    part_of_speech: "noun",
    cefr_level: "A2",
    frequency_rank: 360,
    definition_en: "A complex of runways and buildings for the takeoff, landing, and maintenance of civil aircraft.",
    definition_tr: "Havalimanı, havaalanı.",
    phonetic: "/ˈerpɔːrt/",
    example_sentences: ["We need to be at the airport two hours before departure.", "The airport is far from downtown."],
    collocations: ["airport security", "international airport", "airport shuttle"],
    category: "travel"
  },
  {
    id: 64,
    word: "station",
    part_of_speech: "noun",
    cefr_level: "A2",
    frequency_rank: 315,
    definition_en: "A regular stopping place on a public transportation route, especially one on a railroad line.",
    definition_tr: "İstasyon, gar, durak.",
    phonetic: "/ˈsteɪʃn/",
    example_sentences: ["Meet me at the central train station.", "The next metro station is our stop."],
    collocations: ["train station", "police station", "bus station", "gas station"],
    category: "travel"
  },
  {
    id: 65,
    word: "invite",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 510,
    definition_en: "To make a polite, formal, or friendly request to someone to go somewhere or do something.",
    definition_tr: "Davet etmek, çağırmak.",
    phonetic: "/ɪnˈvaɪt/",
    example_sentences: ["I invited twenty people to my birthday party.", "Thanks for inviting me."],
    collocations: ["invite to dinner", "invite someone over", "send an invite"],
    category: "communication"
  },
  {
    id: 66,
    word: "enjoy",
    part_of_speech: "verb",
    cefr_level: "A2",
    frequency_rank: 270,
    definition_en: "To take delight or pleasure in an activity or occasion.",
    definition_tr: "Zevk almak, keyfini çıkarmak.",
    phonetic: "/ɪnˈdʒɔɪ/",
    example_sentences: ["I really enjoy swimming in the sea.", "Enjoy your meal!"],
    collocations: ["enjoy yourself", "enjoy reading", "thoroughly enjoy"],
    category: "emotions"
  },
  {
    id: 67,
    word: "promise",
    part_of_speech: "verb/noun",
    cefr_level: "A2",
    frequency_rank: 430,
    definition_en: "A declaration or assurance that one will do something or that a particular thing will happen.",
    definition_tr: "Söz vermek; söz, vaat.",
    phonetic: "/ˈprɑːmɪs/",
    example_sentences: ["I promise I will arrive on time.", "Keep your promise."],
    collocations: ["make a promise", "keep a promise", "break a promise"],
    category: "communication"
  },
  {
    id: 68,
    word: "hungry",
    part_of_speech: "adjective",
    cefr_level: "A2",
    frequency_rank: 540,
    definition_en: "Feeling or displaying the need for food.",
    definition_tr: "Aç, acıkmış.",
    phonetic: "/ˈhʌŋɡri/",
    example_sentences: ["I am starving hungry after gym.", "Are you hungry yet?"],
    collocations: ["feel hungry", "hungry for success", "go hungry"],
    category: "food"
  },
  {
    id: 69,
    word: "thirsty",
    part_of_speech: "adjective",
    cefr_level: "A2",
    frequency_rank: 630,
    definition_en: "Feeling a need to drink.",
    definition_tr: "Susamış.",
    phonetic: "/ˈθɜːrsti/",
    example_sentences: ["I am very thirsty; may I have some water?", "Running in summer makes you thirsty."],
    collocations: ["feel thirsty", "thirsty work"],
    category: "food"
  },
  {
    id: 70,
    word: "accident",
    part_of_speech: "noun",
    cefr_level: "A2",
    frequency_rank: 495,
    definition_en: "An unfortunate incident that happens unexpectedly and unintentionally, typically resulting in damage or injury.",
    definition_tr: "Kaza, rastlantı.",
    phonetic: "/ˈæksɪdənt/",
    example_sentences: ["Nobody was hurt in the traffic accident.", "I deleted the file by accident."],
    collocations: ["by accident", "traffic accident", "car accident", "prevent accidents"],
    category: "general"
  },

  // ==========================================
  // LEVEL B1: PROFESSIONAL & EXPANDED (35 words)
  // ==========================================
  {
    id: 71,
    word: "achieve",
    part_of_speech: "verb",
    cefr_level: "B1",
    frequency_rank: 450,
    definition_en: "To successfully reach a desired goal, result, or status through effort.",
    definition_tr: "Başarmak, elde etmek, hedefe ulaşmak.",
    phonetic: "/əˈtʃiːv/",
    example_sentences: ["She worked relentlessly to achieve her ambition.", "They achieved outstanding results this quarter."],
    collocations: ["achieve a goal", "achieve success", "achieve greatness"],
    category: "academic"
  },
  {
    id: 72,
    word: "environment",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 350,
    definition_en: "The surroundings or conditions in which a person, animal, or plant lives or operates.",
    definition_tr: "Çevre, ortam.",
    phonetic: "/ɪnˈvaɪrənmənt/",
    example_sentences: ["We must take urgent steps to protect the environment.", "A supportive working environment boosts morale."],
    collocations: ["protect the environment", "natural environment", "working environment", "environmental impact"],
    category: "science"
  },
  {
    id: 73,
    word: "opportunity",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 400,
    definition_en: "A set of circumstances that makes it possible to do something.",
    definition_tr: "Fırsat, olanak.",
    phonetic: "/ˌɑːpərˈtuːnəti/",
    example_sentences: ["This internship is a golden opportunity to gain experience.", "Don't miss this opportunity."],
    collocations: ["golden opportunity", "equal opportunities", "take the opportunity", "career opportunity"],
    category: "business"
  },
  {
    id: 74,
    word: "despite",
    part_of_speech: "preposition",
    cefr_level: "B1",
    frequency_rank: 550,
    definition_en: "Without being affected by; in spite of.",
    definition_tr: "Rağmen, karşın.",
    phonetic: "/dɪˈspaɪt/",
    example_sentences: ["Despite the pouring rain, the marathon went ahead.", "She passed the exam despite feeling sick."],
    collocations: ["despite the fact that", "despite difficulties", "despite everything"],
    category: "academic"
  },
  {
    id: 75,
    word: "increase",
    part_of_speech: "verb/noun",
    cefr_level: "B1",
    frequency_rank: 320,
    definition_en: "To become or make greater in size, amount, intensity, or degree.",
    definition_tr: "Artmak, artırmak (fiil); artış (isim).",
    phonetic: "/ɪnˈkriːs/",
    example_sentences: ["Online sales increased by 30% this year.", "There was a sharp increase in housing prices."],
    collocations: ["increase significantly", "sharp increase", "steady increase", "on the increase"],
    category: "business"
  },
  {
    id: 76,
    word: "suggest",
    part_of_speech: "verb",
    cefr_level: "B1",
    frequency_rank: 380,
    definition_en: "To put forward an idea, proposition, or hypothesis for consideration.",
    definition_tr: "Önermek, tavsiye etmek; ima etmek.",
    phonetic: "/səɡˈdʒest/",
    example_sentences: ["I suggest we schedule a team meeting on Monday.", "What do you suggest we do next?"],
    collocations: ["suggest that", "strongly suggest", "evidence suggests"],
    category: "communication"
  },
  {
    id: 77,
    word: "challenge",
    part_of_speech: "noun/verb",
    cefr_level: "B1",
    frequency_rank: 420,
    definition_en: "A call to take part in a contest or trial of ability; a demanding task.",
    definition_tr: "Zorluk, meydan okuma; zorlamak.",
    phonetic: "/ˈtʃælɪndʒ/",
    example_sentences: ["Learning a new alphabet is a big challenge.", "This new project will challenge our skills."],
    collocations: ["face a challenge", "major challenge", "accept a challenge", "pose a challenge"],
    category: "academic"
  },
  {
    id: 78,
    word: "experience",
    part_of_speech: "noun/verb",
    cefr_level: "B1",
    frequency_rank: 290,
    definition_en: "Practical contact with and observation of facts or events; knowledge gained through this.",
    definition_tr: "Deneyim, tecrübe; tecrübe etmek.",
    phonetic: "/ɪkˈspɪriəns/",
    example_sentences: ["She has five years of experience in project management.", "Traveling alone was an eye-opening experience."],
    collocations: ["gain experience", "hands-on experience", "previous experience", "work experience"],
    category: "business"
  },
  {
    id: 79,
    word: "purpose",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 460,
    definition_en: "The reason for which something is done or created or for which something exists.",
    definition_tr: "Amaç, gaye, maksat.",
    phonetic: "/ˈpɜːrpəs/",
    example_sentences: ["What is the main purpose of this research?", "He did it on purpose to provoke a reaction."],
    collocations: ["on purpose", "main purpose", "for the purpose of", "sense of purpose"],
    category: "academic"
  },
  {
    id: 80,
    word: "solution",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 390,
    definition_en: "A means of solving a problem or dealing with a difficult situation.",
    definition_tr: "Çözüm, çare.",
    phonetic: "/səˈluːʃn/",
    example_sentences: ["Engineers found a cost-effective solution to the power leak.", "There is no simple solution to this problem."],
    collocations: ["find a solution", "effective solution", "practical solution", "come up with a solution"],
    category: "technology"
  },
  {
    id: 81,
    word: "advantage",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 510,
    definition_en: "A condition or circumstance that puts one in a favorable or superior position.",
    definition_tr: "Avantaj, üstünlük, fayda.",
    phonetic: "/ədˈvæntɪdʒ/",
    example_sentences: ["Being bilingual gives you a huge advantage in the global market.", "What are the advantages of remote work?"],
    collocations: ["take advantage of", "competitive advantage", "distinct advantage", "advantages and disadvantages"],
    category: "business"
  },
  {
    id: 82,
    word: "disadvantage",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 680,
    definition_en: "An unfavorable circumstance or condition that reduces the chances of success.",
    definition_tr: "Dezavantaj, sakınca.",
    phonetic: "/ˌdɪsədˈvæntɪdʒ/",
    example_sentences: ["One disadvantage of living in a large city is the high cost of rent.", "He was at a severe disadvantage."],
    collocations: ["at a disadvantage", "major disadvantage", "overcome disadvantages"],
    category: "general"
  },
  {
    id: 83,
    word: "develop",
    part_of_speech: "verb",
    cefr_level: "B1",
    frequency_rank: 310,
    definition_en: "To grow or cause to grow and become more mature, advanced, or elaborate.",
    definition_tr: "Gelişmek, geliştirmek.",
    phonetic: "/dɪˈveləp/",
    example_sentences: ["The company is developing innovative educational software.", "Children develop communication skills rapidly."],
    collocations: ["develop skills", "develop a strategy", "develop over time", "develop software"],
    category: "technology"
  },
  {
    id: 84,
    word: "improve",
    part_of_speech: "verb",
    cefr_level: "B1",
    frequency_rank: 330,
    definition_en: "To make or become better in quality, condition, or competence.",
    definition_tr: "İyileştirmek, geliştirmek, düzelmek.",
    phonetic: "/ɪmˈpruːv/",
    example_sentences: ["Daily listening practice will significantly improve your comprehension.", "His health has improved remarkably."],
    collocations: ["improve significantly", "room for improvement", "improve skills", "improve quality"],
    category: "academic"
  },
  {
    id: 85,
    word: "manage",
    part_of_speech: "verb",
    cefr_level: "B1",
    frequency_rank: 360,
    definition_en: "To be in charge of; to succeed in doing something despite difficulty.",
    definition_tr: "Yönetmek, idare etmek; (bir şeyi) başarmak.",
    phonetic: "/ˈmænɪdʒ/",
    example_sentences: ["She manages a distributed team of engineers.", "How did you manage to get tickets for the concert?"],
    collocations: ["manage time", "manage to do", "manage a business", "manage stress"],
    category: "business"
  },
  {
    id: 86,
    word: "provide",
    part_of_speech: "verb",
    cefr_level: "B1",
    frequency_rank: 270,
    definition_en: "To make available for use; to supply.",
    definition_tr: "Sağlamak, temin etmek, sunmak.",
    phonetic: "/prəˈvaɪd/",
    example_sentences: ["The platform provides personalized feedback on your pronunciation.", "Can you provide more details?"],
    collocations: ["provide information", "provide support", "provide an opportunity", "provided that"],
    category: "business"
  },
  {
    id: 87,
    word: "necessary",
    part_of_speech: "adjective",
    cefr_level: "B1",
    frequency_rank: 410,
    definition_en: "Required to be done, achieved, or present; needed; essential.",
    definition_tr: "Gerekli, zorunlu, lüzumlu.",
    phonetic: "/ˈnesəseri/",
    example_sentences: ["Patience is necessary when mastering a foreign language.", "Take all necessary precautions."],
    collocations: ["necessary steps", "if necessary", "absolutely necessary", "deem necessary"],
    category: "academic"
  },
  {
    id: 88,
    word: "successful",
    part_of_speech: "adjective",
    cefr_level: "B1",
    frequency_rank: 440,
    definition_en: "Accomplishing an aim or purpose; having achieved popularity or financial success.",
    definition_tr: "Başarılı.",
    phonetic: "/səkˈsesfl/",
    example_sentences: ["He launched a highly successful technology startup.", "The marketing campaign was very successful."],
    collocations: ["highly successful", "successful career", "prove successful"],
    category: "business"
  },
  {
    id: 89,
    word: "reliable",
    part_of_speech: "adjective",
    cefr_level: "B1",
    frequency_rank: 650,
    definition_en: "Consistently good in quality or performance; able to be trusted.",
    definition_tr: "Güvenilir, sağlam.",
    phonetic: "/rɪˈlaɪəbl/",
    example_sentences: ["We need a reliable internet connection for live video calls.", "She is a punctual and reliable colleague."],
    collocations: ["reliable source", "reliable data", "highly reliable", "reliable friend"],
    category: "business"
  },
  {
    id: 90,
    word: "community",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 340,
    definition_en: "A group of people living in the same place or having a particular characteristic in common.",
    definition_tr: "Topluluk, camia, halk.",
    phonetic: "/kəˈmjuːnəti/",
    example_sentences: ["Our online learning community supports members worldwide.", "Local community centers offer free lessons."],
    collocations: ["sense of community", "local community", "global community", "community service"],
    category: "daily_life"
  },
  {
    id: 91,
    word: "behavior",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 520,
    definition_en: "The way in which one acts or conducts oneself, especially toward others.",
    definition_tr: "Davranış, tutum, hareket tarzı.",
    phonetic: "/bɪˈheɪvjər/",
    example_sentences: ["Teachers praised the students for their exemplary behavior.", "Consumer behavior has shifted toward online shopping."],
    collocations: ["consumer behavior", "acceptable behavior", "pattern of behavior"],
    category: "academic"
  },
  {
    id: 92,
    word: "creative",
    part_of_speech: "adjective",
    cefr_level: "B1",
    frequency_rank: 590,
    definition_en: "Relating to or involving the imagination or original ideas.",
    definition_tr: "Yaratıcı, özgün.",
    phonetic: "/kriˈeɪtɪv/",
    example_sentences: ["She found a creative approach to resolve the client's dilemma.", "Creative writing enhances vocabulary retention."],
    collocations: ["creative thinking", "creative solution", "creative industry", "creative writing"],
    category: "general"
  },
  {
    id: 93,
    word: "confident",
    part_of_speech: "adjective",
    cefr_level: "B1",
    frequency_rank: 570,
    definition_en: "Feeling or showing certainty about something or confidence in oneself.",
    definition_tr: "Kendinden emin, özgüvenli.",
    phonetic: "/ˈkɑːnfɪdənt/",
    example_sentences: ["With regular speaking practice, you will become more confident.", "I feel confident about passing the exam."],
    collocations: ["feel confident", "confident about", "self-confident", "confident speaker"],
    category: "emotions"
  },
  {
    id: 94,
    word: "independent",
    part_of_speech: "adjective",
    cefr_level: "B1",
    frequency_rank: 480,
    definition_en: "Free from outside control; not depending on another's authority or financial support.",
    definition_tr: "Bağımsız, kendi başına hareket edebilen.",
    phonetic: "/ˌɪndɪˈpendənt/",
    example_sentences: ["Autonomous study empowers students to become independent learners.", "The country became independent in 1947."],
    collocations: ["independent thinker", "financially independent", "independent of"],
    category: "academic"
  },
  {
    id: 95,
    word: "however",
    part_of_speech: "adverb",
    cefr_level: "B1",
    frequency_rank: 150,
    definition_en: "Used to introduce a statement that contrasts with or seems to contradict something that has been said.",
    definition_tr: "Ancak, bununla birlikte, yine de.",
    phonetic: "/haʊˈevər/",
    example_sentences: ["He studied very hard; however, the test was exceptionally difficult.", "This is useful. However, we need more evidence."],
    collocations: ["however you look at it", "however much"],
    category: "academic"
  },
  {
    id: 96,
    word: "although",
    part_of_speech: "conjunction",
    cefr_level: "B1",
    frequency_rank: 210,
    definition_en: "In spite of the fact that; even though.",
    definition_tr: "-e rağmen, -sa da, gerçi.",
    phonetic: "/ɔːlˈðoʊ/",
    example_sentences: ["Although English grammar can seem complex at first, patterns become second nature.", "She went to work although she felt ill."],
    collocations: ["although it is true", "although rare"],
    category: "academic"
  },
  {
    id: 97,
    word: "furthermore",
    part_of_speech: "adverb",
    cefr_level: "B1",
    frequency_rank: 690,
    definition_en: "In addition; moreover (used to introduce a fresh consideration).",
    definition_tr: "Ayrıca, dahası, üstelik.",
    phonetic: "/ˈfɜːrðərmɔːr/",
    example_sentences: ["The product is energy efficient; furthermore, it comes with a lifetime guarantee.", "Furthermore, the cost is minimal."],
    collocations: ["and furthermore", "furthermore it must be noted"],
    category: "academic"
  },
  {
    id: 98,
    word: "definitely",
    part_of_speech: "adverb",
    cefr_level: "B1",
    frequency_rank: 430,
    definition_en: "Without doubt; clearly or unambiguously.",
    definition_tr: "Kesinlikle, mutlaka.",
    phonetic: "/ˈdefɪnətli/",
    example_sentences: ["I will definitely attend the speaking workshop tomorrow.", "That was definitely the best movie of the year."],
    collocations: ["definitely recommend", "most definitely", "definitely worth it"],
    category: "communication"
  },
  {
    id: 99,
    word: "obviously",
    part_of_speech: "adverb",
    cefr_level: "B1",
    frequency_rank: 470,
    definition_en: "In a way that is easily perceived or understood; clearly.",
    definition_tr: "Açıkça, besbelli, apaçık.",
    phonetic: "/ˈɑːbviəsli/",
    example_sentences: ["Obviously, consistent daily effort yields the highest language retention.", "He was obviously delighted with the outcome."],
    collocations: ["obviously wrong", "quite obviously", "obviously important"],
    category: "communication"
  },
  {
    id: 100,
    word: "convenient",
    part_of_speech: "adjective",
    cefr_level: "B1",
    frequency_rank: 640,
    definition_en: "Fitting in well with a person's needs, activities, and plans; easy to use.",
    definition_tr: "Kullanışlı, elverişli, pratik.",
    phonetic: "/kənˈviːniənt/",
    example_sentences: ["Online learning is very convenient for busy professionals.", "Is Friday morning convenient for you?"],
    collocations: ["convenient location", "convenient time", "convenient way"],
    category: "daily_life"
  },
  {
    id: 101,
    word: "suitable",
    part_of_speech: "adjective",
    cefr_level: "B1",
    frequency_rank: 560,
    definition_en: "Right or appropriate for a particular person, purpose, or situation.",
    definition_tr: "Uygun, münasip, elverişli.",
    phonetic: "/ˈsuːtəbl/",
    example_sentences: ["This reading material is suitable for intermediate students.", "Wear clothes suitable for a job interview."],
    collocations: ["suitable for", "suitable candidate", "mutually suitable"],
    category: "general"
  },
  {
    id: 102,
    word: "culture",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 335,
    definition_en: "The customs, arts, social institutions, and achievements of a particular nation or social group.",
    definition_tr: "Kültür, medeniyet.",
    phonetic: "/ˈkʌltʃər/",
    example_sentences: ["Learning a language involves discovering its culture and idioms.", "Corporate culture plays a big role in job satisfaction."],
    collocations: ["corporate culture", "pop culture", "cultural differences", "diverse culture"],
    category: "academic"
  },
  {
    id: 103,
    word: "technology",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 300,
    definition_en: "The application of scientific knowledge for practical purposes, especially in industry.",
    definition_tr: "Teknoloji.",
    phonetic: "/tekˈnɑːlədʒi/",
    example_sentences: ["Modern technology enables instant speech-to-text feedback.", "Advances in technology are transforming daily life."],
    collocations: ["modern technology", "cutting-edge technology", "technology sector"],
    category: "technology"
  },
  {
    id: 104,
    word: "education",
    part_of_speech: "noun",
    cefr_level: "B1",
    frequency_rank: 280,
    definition_en: "The process of receiving or giving systematic instruction, especially at a school or university.",
    definition_tr: "Eğitim, öğretim.",
    phonetic: "/ˌedʒuˈkeɪʃn/",
    example_sentences: ["Access to quality education is a universal human right.", "Higher education opens doors to international careers."],
    collocations: ["higher education", "quality education", "education system", "pursue education"],
    category: "academic"
  },
  {
    id: 105,
    word: "participate",
    part_of_speech: "verb",
    cefr_level: "B1",
    frequency_rank: 610,
    definition_en: "To take part in an action, discussion, or event.",
    definition_tr: "Katılmak, iştirak etmek.",
    phonetic: "/pɑːrˈtɪsɪpeɪt/",
    example_sentences: ["Students are encouraged to actively participate in group debates.", "Hundreds of athletes participated in the event."],
    collocations: ["participate in", "actively participate", "right to participate"],
    category: "communication"
  },

  // ==========================================
  // LEVEL B2: UPPER INTERMEDIATE / PROFESSIONAL (30 words)
  // ==========================================
  {
    id: 106,
    word: "collaborate",
    part_of_speech: "verb",
    cefr_level: "B2",
    frequency_rank: 820,
    definition_en: "To work jointly on an activity or project to produce an outcome.",
    definition_tr: "İş birliği yapmak, ortaklaşa çalışmak.",
    phonetic: "/kəˈlæbəreɪt/",
    example_sentences: ["Our cross-functional teams collaborate closely on software releases.", "Scientists collaborated across continents to decode the genome."],
    collocations: ["collaborate on", "collaborate with", "collaborate closely"],
    category: "business"
  },
  {
    id: 107,
    word: "distinguish",
    part_of_speech: "verb",
    cefr_level: "B2",
    frequency_rank: 750,
    definition_en: "To recognize or treat someone or something as different; to perceive clearly.",
    definition_tr: "Ayırt etmek, farkı görmek; öne çıkmak.",
    phonetic: "/dɪˈstɪŋɡwɪʃ/",
    example_sentences: ["It is crucial to distinguish between verifiable facts and mere subjective speculation.", "His dedication distinguished him from peers."],
    collocations: ["distinguish between", "distinguish from", "clearly distinguish"],
    category: "academic"
  },
  {
    id: 108,
    word: "evaluate",
    part_of_speech: "verb",
    cefr_level: "B2",
    frequency_rank: 690,
    definition_en: "To form an idea of the amount, number, or value of; to assess critically.",
    definition_tr: "Değerlendirmek, ölçüp biçmek.",
    phonetic: "/ɪˈvæljueɪt/",
    example_sentences: ["The panel will evaluate each proposal based on feasibility and innovation.", "We constantly evaluate our curriculum to ensure relevance."],
    collocations: ["evaluate performance", "evaluate effectiveness", "carefully evaluate"],
    category: "business"
  },
  {
    id: 109,
    word: "facilitate",
    part_of_speech: "verb",
    cefr_level: "B2",
    frequency_rank: 880,
    definition_en: "To make an action or process easy or easier.",
    definition_tr: "Kolaylaştırmak, önünü açmak.",
    phonetic: "/fəˈsɪlɪteɪt/",
    example_sentences: ["Modern digital tools facilitate rapid collaboration among remote teams.", "The moderator facilitated a lively and balanced debate."],
    collocations: ["facilitate learning", "facilitate growth", "facilitate discussion"],
    category: "business"
  },
  {
    id: 110,
    word: "generate",
    part_of_speech: "verb",
    cefr_level: "B2",
    frequency_rank: 630,
    definition_en: "To produce or create something, especially electricity, revenue, or ideas.",
    definition_tr: "Üretmek, meydana getirmek, oluşturmak.",
    phonetic: "/ˈdʒenəreɪt/",
    example_sentences: ["The marketing campaign generated thousands of qualified leads.", "Wind turbines generate clean, renewable power."],
    collocations: ["generate revenue", "generate ideas", "generate excitement"],
    category: "business"
  },
  {
    id: 111,
    word: "implement",
    part_of_speech: "verb",
    cefr_level: "B2",
    frequency_rank: 710,
    definition_en: "To put a decision, plan, or agreement into effect.",
    definition_tr: "Uygulamak, yürürlüğe koymak, hayata geçirmek.",
    phonetic: "/ˈɪmplɪment/",
    example_sentences: ["The management decided to implement flexible working hours.", "We successfully implemented the new security protocol."],
    collocations: ["implement a strategy", "implement changes", "implement policy"],
    category: "business"
  },
  {
    id: 112,
    word: "negotiate",
    part_of_speech: "verb",
    cefr_level: "B2",
    frequency_rank: 790,
    definition_en: "To try to reach an agreement or compromise by discussion.",
    definition_tr: "Müzakere etmek, pazarlık yapmak.",
    phonetic: "/nɪˈɡoʊʃieɪt/",
    example_sentences: ["She successfully negotiated a higher starting salary.", "Diplomats are working around the clock to negotiate a ceasefire."],
    collocations: ["negotiate a contract", "negotiate terms", "negotiate successfully"],
    category: "business"
  },
  {
    id: 113,
    word: "consequence",
    part_of_speech: "noun",
    cefr_level: "B2",
    frequency_rank: 670,
    definition_en: "A result or effect of an action or condition.",
    definition_tr: "Sonuç, netice (özellikle olumsuz netice).",
    phonetic: "/ˈkɑːnsəkwens/",
    example_sentences: ["Every decision we make in business carries lasting consequences.", "Rising sea levels are a dire consequence of climate change."],
    collocations: ["as a consequence", "serious consequence", "unintended consequences"],
    category: "academic"
  },
  {
    id: 114,
    word: "perspective",
    part_of_speech: "noun",
    cefr_level: "B2",
    frequency_rank: 640,
    definition_en: "A particular attitude toward or way of regarding something; a point of view.",
    definition_tr: "Bakış açısı, perspektif.",
    phonetic: "/pərˈspektɪv/",
    example_sentences: ["Traveling broadens your perspective on cultural values.", "From a financial perspective, the merger makes complete sense."],
    collocations: ["from my perspective", "gain perspective", "different perspective", "put into perspective"],
    category: "academic"
  },
  {
    id: 115,
    word: "priority",
    part_of_speech: "noun",
    cefr_level: "B2",
    frequency_rank: 610,
    definition_en: "The fact or condition of being regarded or treated as more important than others.",
    definition_tr: "Öncelik.",
    phonetic: "/praɪˈɔːrəti/",
    example_sentences: ["Customer safety must always remain our top priority.", "You need to reorganize your daily priorities."],
    collocations: ["top priority", "give priority to", "set priorities", "high priority"],
    category: "business"
  },
  {
    id: 116,
    word: "strategy",
    part_of_speech: "noun",
    cefr_level: "B2",
    frequency_rank: 550,
    definition_en: "A plan of action designed to achieve a long-term or overall aim.",
    definition_tr: "Strateji, plan.",
    phonetic: "/ˈstrætədʒi/",
    example_sentences: ["We developed a comprehensive strategy to enter the European market.", "A clear strategy reduces operational friction."],
    collocations: ["marketing strategy", "long-term strategy", "adopt a strategy", "business strategy"],
    category: "business"
  },
  {
    id: 117,
    word: "phenomenon",
    part_of_speech: "noun",
    cefr_level: "B2",
    frequency_rank: 920,
    definition_en: "A fact or situation that is observed to exist or happen, especially one whose cause is in question.",
    definition_tr: "Fenomen, olgu, olağanüstü olay.",
    phonetic: "/fəˈnɑːmɪnən/",
    example_sentences: ["Social media addiction is an unprecedented psychological phenomenon.", "Northern Lights are a spectacular natural phenomenon."],
    collocations: ["natural phenomenon", "cultural phenomenon", "widespread phenomenon"],
    category: "science"
  },
  {
    id: 118,
    word: "infrastructure",
    part_of_speech: "noun",
    cefr_level: "B2",
    frequency_rank: 870,
    definition_en: "The basic physical and organizational structures and facilities needed for the operation of a society or enterprise.",
    definition_tr: "Altyapı.",
    phonetic: "/ˈɪnfrəstrʌktʃər/",
    example_sentences: ["The nation invested billions into renewable energy and transport infrastructure.", "Cloud computing provides resilient IT infrastructure."],
    collocations: ["critical infrastructure", "transport infrastructure", "build infrastructure"],
    category: "business"
  },
  {
    id: 119,
    word: "consensus",
    part_of_speech: "noun",
    cefr_level: "B2",
    frequency_rank: 990,
    definition_en: "A general agreement among members of a group.",
    definition_tr: "Fikir birliği, mutabakat, uzlaşma.",
    phonetic: "/kənˈsensəs/",
    example_sentences: ["After hours of debate, the board reached a unanimous consensus.", "There is broad scientific consensus on global warming."],
    collocations: ["reach a consensus", "general consensus", "build a consensus"],
    category: "business"
  },
  {
    id: 120,
    word: "accurate",
    part_of_speech: "adjective",
    cefr_level: "B2",
    frequency_rank: 660,
    definition_en: "Correct in all details; exact.",
    definition_tr: "Doğru, kesin, hatasız.",
    phonetic: "/ˈækjərət/",
    example_sentences: ["Ensure your financial reports contain accurate figures.", "Scientists made remarkably accurate predictions."],
    collocations: ["accurate description", "highly accurate", "accurate information"],
    category: "academic"
  },
  {
    id: 121,
    word: "comprehensive",
    part_of_speech: "adjective",
    cefr_level: "B2",
    frequency_rank: 780,
    definition_en: "Complete; including all or nearly all elements or aspects of something.",
    definition_tr: "Kapsamlı, etraflı, eksiksiz.",
    phonetic: "/ˌkɑːmprɪˈhensɪv/",
    example_sentences: ["The academy offers a comprehensive guide to English idioms.", "We conducted a comprehensive audit of all accounts."],
    collocations: ["comprehensive study", "comprehensive review", "comprehensive guide"],
    category: "academic"
  },
  {
    id: 122,
    word: "crucial",
    part_of_speech: "adjective",
    cefr_level: "B2",
    frequency_rank: 720,
    definition_en: "Decisive or critical, especially in the success or failure of something.",
    definition_tr: "Çok önemli, hayati, kritik.",
    phonetic: "/ˈkruːʃl/",
    example_sentences: ["Active listening is a crucial ingredient of successful diplomacy.", "The next 48 hours will be crucial for the patient."],
    collocations: ["crucial role", "crucial factor", "crucial decision", "play a crucial role"],
    category: "general"
  },
  {
    id: 123,
    word: "inevitable",
    part_of_speech: "adjective",
    cefr_level: "B2",
    frequency_rank: 830,
    definition_en: "Certain to happen; unavoidable.",
    definition_tr: "Kaçınılmaz, çaresiz.",
    phonetic: "/ɪnˈevɪtəbl/",
    example_sentences: ["Change is an inevitable part of career progression.", "With such heavy traffic, delays were inevitable."],
    collocations: ["inevitable outcome", "seem inevitable", "inevitable result"],
    category: "general"
  },
  {
    id: 124,
    word: "plausible",
    part_of_speech: "adjective",
    cefr_level: "B2",
    frequency_rank: 1050,
    definition_en: "Seeming reasonable or probable; believable.",
    definition_tr: "Makul, akla yatkın, olası.",
    phonetic: "/ˈplɔːzəbl/",
    example_sentences: ["She offered a completely plausible explanation for the discrepancy.", "Is this timeline really plausible given current staffing?"],
    collocations: ["plausible explanation", "perfectly plausible", "plausible scenario"],
    category: "academic"
  },
  {
    id: 125,
    word: "sustainable",
    part_of_speech: "adjective",
    cefr_level: "B2",
    frequency_rank: 840,
    definition_en: "Able to be maintained at a certain rate or level; conserving an ecological balance.",
    definition_tr: "Sürdürülebilir, çevreye duyarlı.",
    phonetic: "/səˈsteɪnəbl/",
    example_sentences: ["Companies must adopt sustainable manufacturing practices.", "Economic growth must be socially and environmentally sustainable."],
    collocations: ["sustainable development", "sustainable future", "sustainable energy"],
    category: "science"
  },
  {
    id: 126,
    word: "versatile",
    part_of_speech: "adjective",
    cefr_level: "B2",
    frequency_rank: 1120,
    definition_en: "Able to adapt or be adapted to many different functions or activities.",
    definition_tr: "Çok yönlü, becerikli, çok amaçlı.",
    phonetic: "/ˈvɜːrsətl/",
    example_sentences: ["He is an exceptionally versatile actor who excels in both drama and comedy.", "Python is one of the most versatile programming languages."],
    collocations: ["versatile actor", "versatile tool", "highly versatile"],
    category: "general"
  },
  {
    id: 127,
    word: "consequently",
    part_of_speech: "adverb",
    cefr_level: "B2",
    frequency_rank: 770,
    definition_en: "As a result; therefore.",
    definition_tr: "Sonuç olarak, bu nedenle, binaenaleyh.",
    phonetic: "/ˈkɑːnsəkwentli/",
    example_sentences: ["The budget was slashed; consequently, several planned projects were halted.", "He failed to prepare, and consequently missed the promotion."],
    collocations: ["and consequently", "consequently led to"],
    category: "academic"
  },
  {
    id: 128,
    word: "nevertheless",
    part_of_speech: "adverb",
    cefr_level: "B2",
    frequency_rank: 790,
    definition_en: "In spite of that; notwithstanding; all the same.",
    definition_tr: "Yine de, buna rağmen, ne var ki.",
    phonetic: "/ˌnevərðəˈles/",
    example_sentences: ["The climb was dangerous; nevertheless, they persevered to the summit.", "It was a tough interview; nevertheless, she remained poised."],
    collocations: ["but nevertheless", "nevertheless true"],
    category: "academic"
  },
  {
    id: 129,
    word: "substantially",
    part_of_speech: "adverb",
    cefr_level: "B2",
    frequency_rank: 910,
    definition_en: "To a great or significant extent; considerably.",
    definition_tr: "Büyük ölçüde, önemli derecede.",
    phonetic: "/səbˈstænʃəli/",
    example_sentences: ["Quality of life has improved substantially over recent decades.", "The new engine is substantially quieter and more fuel efficient."],
    collocations: ["substantially higher", "substantially different", "increase substantially"],
    category: "business"
  },
  {
    id: 130,
    word: "ambiguous",
    part_of_speech: "adjective",
    cefr_level: "B2",
    frequency_rank: 1040,
    definition_en: "Open to more than one interpretation; having a double meaning; unclear.",
    definition_tr: "Muğlak, belirsiz, iki anlamlı.",
    phonetic: "/æmˈbɪɡjuəs/",
    example_sentences: ["The contract clauses were intentionally ambiguous, leading to dispute.", "Her reply was frustratingly ambiguous."],
    collocations: ["ambiguous statement", "remain ambiguous", "morally ambiguous"],
    category: "academic"
  },
  {
    id: 131,
    word: "substitute",
    part_of_speech: "verb/noun",
    cefr_level: "B2",
    frequency_rank: 860,
    definition_en: "To use or add in place of; a person or thing that takes the place of another.",
    definition_tr: "Yerine koymak, ikame etmek; yedek.",
    phonetic: "/ˈsʌbstɪtuːt/",
    example_sentences: ["You can substitute olive oil for butter in this recipe.", "There is no substitute for hard work."],
    collocations: ["substitute for", "act as a substitute", "substitute teacher"],
    category: "general"
  },
  {
    id: 132,
    word: "legislation",
    part_of_speech: "noun",
    cefr_level: "B2",
    frequency_rank: 940,
    definition_en: "Laws, considered collectively; the process of making or enacting laws.",
    definition_tr: "Mevzuat, yasalar, kanun yapımı.",
    phonetic: "/ˌledʒɪsˈleɪʃn/",
    example_sentences: ["Parliament passed landmark legislation on environmental emissions.", "New labor legislation protects remote gig workers."],
    collocations: ["pass legislation", "introduce legislation", "under existing legislation"],
    category: "academic"
  },
  {
    id: 133,
    word: "predominantly",
    part_of_speech: "adverb",
    cefr_level: "B2",
    frequency_rank: 1080,
    definition_en: "Mainly; for the most part.",
    definition_tr: "Ağırlıklı olarak, çoğunlukla, başta olmak üzere.",
    phonetic: "/prɪˈdɑːmɪnəntli/",
    example_sentences: ["The local economy is predominantly based on agricultural exports.", "The audience was composed predominantly of university students."],
    collocations: ["predominantly male/female", "predominantly rural"],
    category: "academic"
  },
  {
    id: 134,
    word: "spontaneously",
    part_of_speech: "adverb",
    cefr_level: "B2",
    frequency_rank: 1150,
    definition_en: "As a result of a sudden impulse and without premeditation or external stimulus.",
    definition_tr: "Kendiliğinden, aniden, doğal olarak.",
    phonetic: "/spɑːnˈteɪniəsli/",
    example_sentences: ["The crowd began to sing spontaneously at the conclusion of the concert.", "Children often speak spontaneously without self-censorship."],
    collocations: ["arise spontaneously", "occur spontaneously", "act spontaneously"],
    category: "emotions"
  },
  {
    id: 135,
    word: "accommodate",
    part_of_speech: "verb",
    cefr_level: "B2",
    frequency_rank: 890,
    definition_en: "To provide lodging or sufficient space for; to adapt to someone's wishes.",
    definition_tr: "Barındırmak, yer sağlamak; ayak uydurmak.",
    phonetic: "/əˈkɑːmədeɪt/",
    example_sentences: ["The auditorium can easily accommodate up to 800 attendees.", "We will do our utmost to accommodate your schedule."],
    collocations: ["accommodate needs", "accommodate guests", "accommodate changes"],
    category: "business"
  },

  // ==========================================
  // LEVEL C1/C2: ADVANCED & MASTERY (20 words)
  // ==========================================
  {
    id: 136,
    word: "articulate",
    part_of_speech: "verb/adjective",
    cefr_level: "C1",
    frequency_rank: 1250,
    definition_en: "To express an idea or feeling fluently and coherently; having the ability to speak fluently.",
    definition_tr: "Düşüncelerini net ifade etmek; açık, anlaşılır, fasih.",
    phonetic: "/ɑːrˈtɪkjuleɪt/",
    example_sentences: ["She articulated her vision with remarkable precision and passion.", "He is an articulate advocate for civil liberties."],
    collocations: ["articulate clearly", "highly articulate", "articulate vision"],
    category: "communication"
  },
  {
    id: 137,
    word: "substantiate",
    part_of_speech: "verb",
    cefr_level: "C1",
    frequency_rank: 1400,
    definition_en: "To provide evidence to support or prove the truth of a claim.",
    definition_tr: "Somut kanıtlarla doğrulamak, kanıtlamak.",
    phonetic: "/səbˈstænʃieɪt/",
    example_sentences: ["The investigator failed to substantiate the allegations with credible data.", "Can you substantiate that thesis with empirical research?"],
    collocations: ["substantiate claims", "substantiate allegations", "substantiate with evidence"],
    category: "academic"
  },
  {
    id: 138,
    word: "scrutinize",
    part_of_speech: "verb",
    cefr_level: "C1",
    frequency_rank: 1350,
    definition_en: "To examine or inspect closely and thoroughly.",
    definition_tr: "En ince ayrıntısına kadar incelemek, denetlemek.",
    phonetic: "/ˈskruːtənaɪz/",
    example_sentences: ["The regulatory agency scrutinized every financial transaction.", "Journalists scrutinized the government's foreign policy record."],
    collocations: ["scrutinize closely", "scrutinize carefully", "scrutinize data"],
    category: "academic"
  },
  {
    id: 139,
    word: "exacerbate",
    part_of_speech: "verb",
    cefr_level: "C1",
    frequency_rank: 1450,
    definition_en: "To make a problem, bad situation, or negative feeling worse.",
    definition_tr: "Daha da kötüleştirmek, şiddetlendirmek, tırmandırmak.",
    phonetic: "/ɪɡˈzæsərbeɪt/",
    example_sentences: ["Inflation and high interest rates exacerbated the country's housing crisis.", "Her harsh comments only exacerbated tensions."],
    collocations: ["exacerbate the problem", "exacerbate tensions", "exacerbate poverty"],
    category: "academic"
  },
  {
    id: 140,
    word: "advocate",
    part_of_speech: "verb/noun",
    cefr_level: "C1",
    frequency_rank: 1100,
    definition_en: "To publicly recommend or support; a person who puts forward a cause.",
    definition_tr: "Savunmak, desteklemek; savunucu, dava vekili.",
    phonetic: "/ˈædvəkeɪt/",
    example_sentences: ["Doctors strongly advocate a reduction in refined sugar intake.", "She has been a fierce advocate for renewable energy."],
    collocations: ["strongly advocate", "advocate for", "fierce advocate"],
    category: "academic"
  },
  {
    id: 141,
    word: "delineate",
    part_of_speech: "verb",
    cefr_level: "C1",
    frequency_rank: 1550,
    definition_en: "To describe or portray something precisely; to indicate the exact position of a boundary.",
    definition_tr: "Ayrıntılarıyla tasvir etmek, sınırlarını çizmek.",
    phonetic: "/dɪˈlɪnieɪt/",
    example_sentences: ["The report delineates the clear steps required to achieve carbon neutrality.", "The law delineates the responsibilities of both parties."],
    collocations: ["clearly delineate", "delineate boundaries", "delineate roles"],
    category: "academic"
  },
  {
    id: 142,
    word: "reconcile",
    part_of_speech: "verb",
    cefr_level: "C1",
    frequency_rank: 1200,
    definition_en: "To restore friendly relations between; to make consistent or compatible.",
    definition_tr: "Uzlaştırmak, arayı bulmak; bağdaştırmak.",
    phonetic: "/ˈrekənsaɪl/",
    example_sentences: ["It was difficult to reconcile his personal principles with corporate demands.", "The two factions reconciled after extensive mediation."],
    collocations: ["reconcile differences", "reconcile with", "hard to reconcile"],
    category: "communication"
  },
  {
    id: 143,
    word: "paradigm",
    part_of_speech: "noun",
    cefr_level: "C1",
    frequency_rank: 1300,
    definition_en: "A typical example or pattern of something; a model or worldview.",
    definition_tr: "Paradigma, model, temel dünya görüşü.",
    phonetic: "/ˈpærədaɪm/",
    example_sentences: ["The advent of generative AI represents a monumental paradigm shift.", "We need to operate within a new economic paradigm."],
    collocations: ["paradigm shift", "dominant paradigm", "new paradigm"],
    category: "academic"
  },
  {
    id: 144,
    word: "discrepancy",
    part_of_speech: "noun",
    cefr_level: "C1",
    frequency_rank: 1280,
    definition_en: "A lack of compatibility or similarity between two or more facts.",
    definition_tr: "Çelişki, uyuşmazlık, tutarsızlık.",
    phonetic: "/dɪˈskrepənsi/",
    example_sentences: ["Auditors discovered a conspicuous discrepancy between recorded and actual inventory.", "There is an unresolved discrepancy in the witness statements."],
    collocations: ["significant discrepancy", "apparent discrepancy", "discrepancy between"],
    category: "academic"
  },
  {
    id: 145,
    word: "ubiquitous",
    part_of_speech: "adjective",
    cefr_level: "C1",
    frequency_rank: 1500,
    definition_en: "Present, appearing, or found everywhere.",
    definition_tr: "Her yerde bulunan, yaygın, hazır ve nazır.",
    phonetic: "/juːˈbɪkwɪtəs/",
    example_sentences: ["Smartphones have become ubiquitous in modern metropolitan life.", "Sugar is ubiquitous in processed supermarket foods."],
    collocations: ["become ubiquitous", "ubiquitous presence", "almost ubiquitous"],
    category: "academic"
  },
  {
    id: 146,
    word: "meticulous",
    part_of_speech: "adjective",
    cefr_level: "C1",
    frequency_rank: 1380,
    definition_en: "Showing great attention to detail; very careful and precise.",
    definition_tr: "Titiz, kılı kırk yaran, özenli.",
    phonetic: "/məˈtɪkjələs/",
    example_sentences: ["The restoration of the ancient manuscript required meticulous precision.", "She kept meticulous notes during every laboratory trial."],
    collocations: ["meticulous attention to detail", "meticulous planning", "meticulous research"],
    category: "academic"
  },
  {
    id: 147,
    word: "pragmatic",
    part_of_speech: "adjective",
    cefr_level: "C1",
    frequency_rank: 1180,
    definition_en: "Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.",
    definition_tr: "Pragmatik, uygulamacı, faydacı, ayakları yere basan.",
    phonetic: "/præɡˈmætɪk/",
    example_sentences: ["We adopted a pragmatic approach to solve the deadline crunch.", "He is known as a pragmatic dealmaker in international commerce."],
    collocations: ["pragmatic approach", "pragmatic solution", "pragmatic decision"],
    category: "business"
  },
  {
    id: 148,
    word: "resilient",
    part_of_speech: "adjective",
    cefr_level: "C1",
    frequency_rank: 1220,
    definition_en: "Able to withstand or recover quickly from difficult conditions.",
    definition_tr: "Dirençli, esnek, zorluklara göğüs gerebilen.",
    phonetic: "/rɪˈzɪliənt/",
    example_sentences: ["The local economy proved remarkably resilient throughout the economic crisis.", "Resilient learners view failure as crucial feedback."],
    collocations: ["highly resilient", "resilient economy", "remain resilient"],
    category: "emotions"
  },
  {
    id: 149,
    word: "compelling",
    part_of_speech: "adjective",
    cefr_level: "C1",
    frequency_rank: 1160,
    definition_en: "Evoking interest, attention, or admiration in a powerfully irresistible way.",
    definition_tr: "İkna edici, büyüleyici, karşı konulmaz.",
    phonetic: "/kəmˈpelɪŋ/",
    example_sentences: ["The defense attorney presented a compelling argument based on surveillance footage.", "Her debut novel tells a compelling and tragic story."],
    collocations: ["compelling evidence", "compelling reason", "compelling argument"],
    category: "communication"
  },
  {
    id: 150,
    word: "nuanced",
    part_of_speech: "adjective",
    cefr_level: "C1",
    frequency_rank: 1420,
    definition_en: "Characterized by subtle shades of meaning or expression.",
    definition_tr: "İnce ayrıntıları barındıran, nüanslı, derinlikli.",
    phonetic: "/ˈnuːɑːnst/",
    example_sentences: ["Complex geopolitical issues require a nuanced and mature perspective.", "His nuanced understanding of English idioms sets him apart."],
    collocations: ["nuanced understanding", "nuanced approach", "highly nuanced"],
    category: "academic"
  },
  {
    id: 151,
    word: "ephemeral",
    part_of_speech: "adjective",
    cefr_level: "C2",
    frequency_rank: 1900,
    definition_en: "Lasting for a very short time; fleeting.",
    definition_tr: "Geçici, fani, kısa ömürlü.",
    phonetic: "/ɪˈfemərəl/",
    example_sentences: ["Fame on social media can be notoriously ephemeral.", "Cherry blossoms represent the ephemeral beauty of springtime."],
    collocations: ["ephemeral nature", "ephemeral beauty", "ephemeral pleasures"],
    category: "academic"
  },
  {
    id: 152,
    word: "superfluous",
    part_of_speech: "adjective",
    cefr_level: "C2",
    frequency_rank: 1850,
    definition_en: "Unnecessary, especially through being more than enough.",
    definition_tr: "Gereksiz, fuzuli, fazlalık.",
    phonetic: "/suːˈpɜːrfluəs/",
    example_sentences: ["Concise business writing eliminates superfluous adjectives.", "The assistant was let go because his role had become superfluous."],
    collocations: ["superfluous details", "render superfluous", "superfluous words"],
    category: "academic"
  },
  {
    id: 153,
    word: "ambivalence",
    part_of_speech: "noun",
    cefr_level: "C2",
    frequency_rank: 1950,
    definition_en: "The state of having mixed feelings or contradictory ideas about something or someone.",
    definition_tr: "İkirciklilik, kararsızlık, çelişik duygular içinde olma.",
    phonetic: "/æmˈbɪvələns/",
    example_sentences: ["She felt acute ambivalence about leaving her hometown for a job in New York.", "There is considerable public ambivalence toward artificial intelligence."],
    collocations: ["feel ambivalence", "sense of ambivalence", "moral ambivalence"],
    category: "emotions"
  },
  {
    id: 154,
    word: "proliferation",
    part_of_speech: "noun",
    cefr_level: "C2",
    frequency_rank: 1750,
    definition_en: "Rapid increase in the number or amount of something; rapid reproduction of an organism.",
    definition_tr: "Hızlı artış, türeme, yayılma.",
    phonetic: "/prəˌlɪfəˈreɪʃn/",
    example_sentences: ["The proliferation of false information poses a grave threat to democracy.", "We have witnessed a proliferation of smartphone apps."],
    collocations: ["rapid proliferation", "proliferation of weapons", "nuclear proliferation"],
    category: "academic"
  },
  {
    id: 155,
    word: "repercussion",
    part_of_speech: "noun",
    cefr_level: "C2",
    frequency_rank: 1680,
    definition_en: "An unintended consequence occurring some time after an event or action, especially an unwelcome one.",
    definition_tr: "Yankı, dolaylı kötü sonuç, ters tepki.",
    phonetic: "/ˌriːpərˈkʌʃn/",
    example_sentences: ["The collapse of the bank had severe economic repercussions across the globe.", "Think carefully about the long-term repercussions."],
    collocations: ["serious repercussions", "economic repercussions", "have repercussions"],
    category: "business"
  }
];
